version: "3.8"

services:
  backend:
    build: 
      context: ./backend  # Adjust if needed
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - ./backend/.env  # Loads environment variables

  frontend:
    build:
      context: ./client  # Adjust if needed
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend  # Ensures backend starts first